debug: false
app_name: Pterodactyl
uuid: UUID
token_id: TOKEN_ID
token: TOKEN
api:
  host: 0.0.0.0
  port: 2096
  ssl:
    enabled: true
    cert: C:\ProgramData\Pterodactyl\fullchain.pem
    key: C:\ProgramData\Pterodactyl\privkey.pem
  disable_remote_download: false
  upload_limit: 100
  trusted_proxies: []
system:
  root_directory: E:\SERVER_MOUNTS\Pterodactyl
  log_directory: E:\SERVER_MOUNTS\Logs
  data: E:\SERVER_MOUNTS\Container
  archive_directory: E:\SERVER_MOUNTS\Archives
  backup_directory: E:\SERVER_MOUNTS\Backups
  tmp_directory: E:\SERVER_MOUNTS\Temp
  username: WINDOWS_ACCOUNTNAME
  timezone: Local
  passwd:
    enabled: false
    directory: C:\ProgramData\Pterodactyl\Passwd
  machine_id:
    enabled: true
    directory: C:\ProgramData\Pterodactyl\MachineId
  disk_check_interval: 150
  activity_send_interval: 60
  activity_send_count: 100
  check_permissions_on_boot: true
  enable_log_rotate: true
  websocket_log_count: 150
  sftp:
    bind_address: 0.0.0.0
    bind_port: 2022
    read_only: false
  crash_detection:
    enabled: true
    detect_clean_exit_as_crash: true
    timeout: 60
  backups:
    write_limit: 0
    compression_level: best_speed
  transfers:
    download_limit: 0
  openat_mode: auto
docker:
  network:
    interface: 172.18.0.1
    dns:
    - 1.1.1.1
    - 1.0.0.1
    name: pterodactyl_nw
    ispn: false
    driver: bridge
    network_mode: pterodactyl_nw
    is_internal: false
    enable_icc: true
    network_mtu: 1500
    interfaces:
      v4:
        subnet: 172.18.0.0/24
        gateway: 172.18.0.1
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
  domainname: ""
  registries: {}
  tmpfs_size: 100
  container_pid_limit: 512
  installer_limits:
    memory: 1024
    cpu: 100
  overhead:
    override: false
    default_multiplier: 1.05
    multipliers: {}
  use_performant_inspect: true
  userns_mode: ""
  log_config:
    type: local
    config:
      compress: "false"
      max-file: "1"
      max-size: 5m
      mode: non-blocking
throttles:
  enabled: true
  lines: 2000
  line_reset_interval: 100
remote: https://YOURPANEL
remote_query:
  timeout: 30
  boot_servers_per_page: 50
allowed_mounts: []
allowed_origins:
- '*'
allow_cors_private_network: true
ignore_panel_config_updates: false
